<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-02-29T00:29:54 IST" name="Default suite" finished-at="2024-02-29T00:30:07 IST" duration-ms="12803">
    <groups>
    </groups>
    <test started-at="2024-02-29T00:29:54 IST" name="Default test" finished-at="2024-02-29T00:30:07 IST" duration-ms="12803">
      <class name="com.crm.qa.testcases.TakeScreenshotOfFailedTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.crm.qa.testcases.TakeScreenshotOfFailedTest@3527942a]" started-at="2024-02-29T00:29:54 IST" name="setUp" finished-at="2024-02-29T00:30:04 IST" duration-ms="9737" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginToCRMApplication()[pri:0, instance:com.crm.qa.testcases.TakeScreenshotOfFailedTest@3527942a]" started-at="2024-02-29T00:30:04 IST" name="loginToCRMApplication" finished-at="2024-02-29T00:30:06 IST" duration-ms="2638" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [CRMPRO1] but found [Free CRM software for customer relationship management, sales, and support.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [CRMPRO1] but found [Free CRM software for customer relationship management, sales, and support.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.crm.qa.testcases.TakeScreenshotOfFailedTest.loginToCRMApplication(TakeScreenshotOfFailedTest.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToCRMApplication -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.crm.qa.testcases.TakeScreenshotOfFailedTest@3527942a]" started-at="2024-02-29T00:30:06 IST" name="tearDown" finished-at="2024-02-29T00:30:07 IST" duration-ms="151" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.crm.qa.testcases.TakeScreenshotOfFailedTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
